### PR TITLE
Add a way to access the custom pointer on OCaml blocks

### PR DESCRIPTION
**Pull request by g2p**
Useful for bigarrays and other custom types.

### CODE REVIEW

**Comment by tizoc** [comment]
Hello @g2p, sorry for the long delay, took me a while to merge the other branch (had other stuff to work on).

How do you use this?

Also, can you rebase on top of the current master?

**Comment by g2p** [comment]
Actual usage is in this branch:
https://github.com/g2p/ocaml-interop/commits/bigarray
As well as the ocamlbox branch.
(I had made it a separate PR since it seemed easier to merge)

I'll rework the various branches to be on top of current master.

**Comment by g2p** [comment]
Usage is here, specifically: https://github.com/g2p/ocaml-interop/blob/bigarray/src/bigarray.rs

**Comment by g2p** [comment]
Rebased; it's also part of #24.

**Comment by tizoc** [comment]
I think this method should be available only on types that implement some kind of `Custom` trait, then in that case it may be possible to make it safer. I'm thinking about merging this one and #24 and mark them as "experimental" for now, because although I am not fully happy with the current implementation, it is useful already and not really that far off from what I would like.

**Pull request merged**
